name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push 2014_x86_64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_2014_x86_64
          platforms: linux/amd64
          push: true
          tags: ghcr.io/q-posev/hdf5_1_12_on_2014_x86_64:latest
      -
        name: Build and push 2_28_x86_64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_2_28_x86_64
          platforms: linux/amd64
          push: true
          tags: ghcr.io/q-posev/hdf5_1_12_on_2_28_x86_64:latest
