name: ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Publish
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          imageName: hdf5_1_12_on_2010_x86_64
          containerRegistry: true
          contextName: ./Dockerfile_2010_x86_64
